### PR TITLE
Add url to partners ACF

### PR DESCRIPTION
**Pull request by KobbyMmo**
## Description

Add URL  Partners Section ACF

Fixes # (N/A)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Desktop Screenshots

image

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by KhadijaMahanga** [comment]
@KobbyMmo lets update the modified time to today https://www.epochconverter.com/ modified field should be at the end of the file

**Review by KhadijaMahanga — APPROVED** [review]
🚀

**Comment by kilemensi** [comment]
> @KobbyMmo lets update the modified time to today https://www.epochconverter.com/ modified field should be at the end of the file

For slow ones like myself, why do we need to do this?

**Review by kilemensi — COMMENTED** [review]
👍🏾 @KobbyMmo 

LGTM but my Internet is just too slow for the docker to complete at the moment & we need to have this fixed as soon as possible.

**Comment by KhadijaMahanga** [comment]
> > @KobbyMmo lets update the modified time to today https://www.epochconverter.com/ modified field should be at the end of the file
> 
> For slow ones like myself, why do we need to do this?

@kilemensi  Why are you asking this in 2021?

`JSON field groups will be available for sync when either the JSON field group does not exist in the DB, or when the JSON field group contains a higher ‘modified’ value (within the JSON array) than the DB post’s modified date.`

**Comment by kilemensi** [comment]
> > > @KobbyMmo lets update the modified time to today https://www.epochconverter.com/ modified field should be at the end of the file
> > 
> > 
> > For slow ones like myself, why do we need to do this?
> 
> @kilemensi Why are you asking this in 2021?
> 
> `JSON field groups will be available for sync when either the JSON field group does not exist in the DB, or when the JSON field group contains a higher ‘modified’ value (within the JSON array) than the DB post’s modified date.`

Shared knowledge @KhadijaMahanga ... shared knowledge. Not everyone was there when the dashboard was built 😎

**Pull request merged**
